ALTER TABLE human_workflow_compile_jobs
  ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_retried_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS timeout_ms INTEGER;
