-- PNQ-001 G1 observe-mode device execution queue.
-- The arbiter is PostgreSQL-authoritative; observe mode records policy decisions
-- without changing the existing dispatcher order.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS device_execution_roots (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id             UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  root_kind             TEXT NOT NULL,
  external_id           TEXT,
  request_key           TEXT,
  state                 TEXT NOT NULL,
  fifo_sequence         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  owner_generation      BIGINT NOT NULL DEFAULT 0,
  observe_mode          BOOLEAN NOT NULL,
  claimed_at            TIMESTAMPTZ,
  dispatching_at        TIMESTAMPTZ,
  dispatched_at         TIMESTAMPTZ,
  terminal_at           TIMESTAMPTZ,
  reconciliation_reason TEXT,
  terminal_reason       TEXT,
  metadata              JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE device_execution_roots
  ADD COLUMN IF NOT EXISTS id UUID DEFAULT gen_random_uuid(),
  ADD COLUMN IF NOT EXISTS device_id UUID,
  ADD COLUMN IF NOT EXISTS root_kind TEXT,
  ADD COLUMN IF NOT EXISTS external_id TEXT,
  ADD COLUMN IF NOT EXISTS request_key TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS fifo_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS owner_generation BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS observe_mode BOOLEAN,
  ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispatching_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispatched_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS terminal_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reconciliation_reason TEXT,
  ADD COLUMN IF NOT EXISTS terminal_reason TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE device_execution_roots
  DROP CONSTRAINT IF EXISTS device_execution_roots_state_check;

ALTER TABLE device_execution_roots
  DROP CONSTRAINT IF EXISTS device_execution_roots_root_kind_check,
  ALTER COLUMN observe_mode DROP DEFAULT;

DO $$
BEGIN
  ALTER TABLE device_execution_roots
    ADD CONSTRAINT device_execution_roots_owner_generation_check
    CHECK (owner_generation >= 0);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_device_execution_roots_external
  ON device_execution_roots(root_kind, external_id)
  WHERE external_id IS NOT NULL;

DROP INDEX IF EXISTS idx_device_execution_active_slot;
DROP INDEX IF EXISTS idx_device_execution_roots_fifo;
CREATE INDEX IF NOT EXISTS idx_device_execution_roots_state_fifo
  ON device_execution_roots(device_id, state, fifo_sequence);

CREATE INDEX IF NOT EXISTS idx_device_execution_roots_device_created
  ON device_execution_roots(device_id, created_at DESC);

CREATE TABLE IF NOT EXISTS device_execution_operations (
  id               BIGSERIAL PRIMARY KEY,
  root_id          UUID NOT NULL REFERENCES device_execution_roots(id) ON DELETE CASCADE,
  device_id        UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  root_kind        TEXT NOT NULL,
  operation_kind   TEXT NOT NULL,
  operation_id     TEXT NOT NULL,
  owner_generation BIGINT NOT NULL DEFAULT 0,
  state            TEXT NOT NULL,
  egress_lane      TEXT NOT NULL,
  wire_type        TEXT,
  wire_handle      JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
  dispatching_at   TIMESTAMPTZ,
  dispatched_at    TIMESTAMPTZ,
  terminal_at      TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE device_execution_operations
  ADD COLUMN IF NOT EXISTS id BIGSERIAL,
  ADD COLUMN IF NOT EXISTS root_id UUID,
  ADD COLUMN IF NOT EXISTS device_id UUID,
  ADD COLUMN IF NOT EXISTS root_kind TEXT,
  ADD COLUMN IF NOT EXISTS operation_kind TEXT,
  ADD COLUMN IF NOT EXISTS operation_id TEXT,
  ADD COLUMN IF NOT EXISTS owner_generation BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS egress_lane TEXT,
  ADD COLUMN IF NOT EXISTS wire_type TEXT,
  ADD COLUMN IF NOT EXISTS wire_handle JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS dispatching_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispatched_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS terminal_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'device_execution_operations_root_id_fkey'
      AND conrelid = 'device_execution_operations'::regclass
  ) THEN
    ALTER TABLE device_execution_operations
      ADD CONSTRAINT device_execution_operations_root_id_fkey
      FOREIGN KEY (root_id) REFERENCES device_execution_roots(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'device_execution_operations_device_id_fkey'
      AND conrelid = 'device_execution_operations'::regclass
  ) THEN
    ALTER TABLE device_execution_operations
      ADD CONSTRAINT device_execution_operations_device_id_fkey
      FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE;
  END IF;
END $$;

ALTER TABLE device_execution_operations
  DROP CONSTRAINT IF EXISTS device_execution_operations_state_check,
  DROP CONSTRAINT IF EXISTS device_execution_operations_root_kind_check,
  DROP CONSTRAINT IF EXISTS device_execution_operations_operation_kind_check,
  DROP CONSTRAINT IF EXISTS device_execution_operations_egress_lane_check,
  ALTER COLUMN egress_lane DROP DEFAULT;

DO $$
BEGIN
  ALTER TABLE device_execution_operations
    DROP CONSTRAINT IF EXISTS device_execution_operations_owner_generation_check;
  ALTER TABLE device_execution_operations
    ADD CONSTRAINT device_execution_operations_owner_generation_check
    CHECK (owner_generation >= 0);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_device_execution_operations_identity
  ON device_execution_operations(operation_kind, operation_id);

CREATE INDEX IF NOT EXISTS idx_device_execution_operations_root
  ON device_execution_operations(root_id, created_at);

CREATE INDEX IF NOT EXISTS idx_device_execution_operations_device
  ON device_execution_operations(device_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_device_execution_operations_state
  ON device_execution_operations(state, updated_at DESC);

CREATE TABLE IF NOT EXISTS device_execution_events (
  id             BIGSERIAL PRIMARY KEY,
  root_id        UUID REFERENCES device_execution_roots(id) ON DELETE SET NULL,
  device_id      UUID REFERENCES devices(id) ON DELETE SET NULL,
  event_type     TEXT NOT NULL,
  previous_state TEXT,
  new_state      TEXT,
  actor          TEXT NOT NULL DEFAULT 'server',
  reason         TEXT,
  metadata       JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE device_execution_events
  ADD COLUMN IF NOT EXISTS id BIGSERIAL,
  ADD COLUMN IF NOT EXISTS root_id UUID,
  ADD COLUMN IF NOT EXISTS device_id UUID,
  ADD COLUMN IF NOT EXISTS event_type TEXT,
  ADD COLUMN IF NOT EXISTS previous_state TEXT,
  ADD COLUMN IF NOT EXISTS new_state TEXT,
  ADD COLUMN IF NOT EXISTS actor TEXT NOT NULL DEFAULT 'server',
  ADD COLUMN IF NOT EXISTS reason TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_device_execution_events_root
  ON device_execution_events(root_id, created_at);

CREATE INDEX IF NOT EXISTS idx_device_execution_events_device
  ON device_execution_events(device_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_device_execution_events_type
  ON device_execution_events(event_type, created_at DESC);
