-- PNQ-001 G1 observe-mode device execution queue.
-- The arbiter is PostgreSQL-authoritative; observe mode records policy decisions
-- without changing the existing dispatcher order.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS device_execution_roots (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id             UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  root_kind             TEXT NOT NULL,
  external_id           TEXT,
  request_key           TEXT,
  state                 TEXT NOT NULL DEFAULT 'queued',
  fifo_sequence         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  owner_generation      BIGINT NOT NULL DEFAULT 0,
  observe_mode          BOOLEAN NOT NULL DEFAULT TRUE,
  claimed_at            TIMESTAMPTZ,
  dispatched_at         TIMESTAMPTZ,
  terminal_at           TIMESTAMPTZ,
  reconciliation_reason TEXT,
  terminal_reason       TEXT,
  metadata              JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE device_execution_roots
  ADD COLUMN IF NOT EXISTS id UUID DEFAULT gen_random_uuid(),
  ADD COLUMN IF NOT EXISTS device_id UUID,
  ADD COLUMN IF NOT EXISTS root_kind TEXT,
  ADD COLUMN IF NOT EXISTS external_id TEXT,
  ADD COLUMN IF NOT EXISTS request_key TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT DEFAULT 'queued',
  ADD COLUMN IF NOT EXISTS fifo_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS owner_generation BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS observe_mode BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispatched_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS terminal_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reconciliation_reason TEXT,
  ADD COLUMN IF NOT EXISTS terminal_reason TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

DO $$
BEGIN
  ALTER TABLE device_execution_roots
    ADD CONSTRAINT device_execution_roots_root_kind_check
    CHECK (root_kind IN ('job', 'batch', 'edge_workflow', 'server_workflow', 'control', 'unknown'));
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE device_execution_roots
    ADD CONSTRAINT device_execution_roots_state_check
    CHECK (state IN ('queued', 'claimed', 'dispatched', 'completed', 'failed', 'cancelled', 'reconciling', 'blocked'));
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE device_execution_roots
    ADD CONSTRAINT device_execution_roots_owner_generation_check
    CHECK (owner_generation >= 0);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_device_execution_roots_external
  ON device_execution_roots(root_kind, external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_device_execution_active_slot
  ON device_execution_roots(device_id)
  WHERE state IN ('claimed', 'dispatched', 'reconciling', 'blocked');

CREATE INDEX IF NOT EXISTS idx_device_execution_roots_fifo
  ON device_execution_roots(device_id, fifo_sequence)
  WHERE state = 'queued';

CREATE INDEX IF NOT EXISTS idx_device_execution_roots_device_created
  ON device_execution_roots(device_id, created_at DESC);

CREATE TABLE IF NOT EXISTS device_execution_events (
  id             BIGSERIAL PRIMARY KEY,
  root_id        UUID REFERENCES device_execution_roots(id) ON DELETE SET NULL,
  device_id      UUID REFERENCES devices(id) ON DELETE SET NULL,
  event_type     TEXT NOT NULL,
  previous_state TEXT,
  new_state      TEXT,
  actor          TEXT NOT NULL DEFAULT 'server',
  reason         TEXT,
  metadata       JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE device_execution_events
  ADD COLUMN IF NOT EXISTS id BIGSERIAL,
  ADD COLUMN IF NOT EXISTS root_id UUID,
  ADD COLUMN IF NOT EXISTS device_id UUID,
  ADD COLUMN IF NOT EXISTS event_type TEXT,
  ADD COLUMN IF NOT EXISTS previous_state TEXT,
  ADD COLUMN IF NOT EXISTS new_state TEXT,
  ADD COLUMN IF NOT EXISTS actor TEXT NOT NULL DEFAULT 'server',
  ADD COLUMN IF NOT EXISTS reason TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_device_execution_events_root
  ON device_execution_events(root_id, created_at);

CREATE INDEX IF NOT EXISTS idx_device_execution_events_device
  ON device_execution_events(device_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_device_execution_events_type
  ON device_execution_events(event_type, created_at DESC);
