/**
 * shared/protocol/messages.ts
 * WebSocket message types shared between server and dashboard.
 * Android agent uses this as reference (Kotlin implementation mirrors these types).
 *
 * Auth model: Dual token (access 24h + refresh 30d) + server-side revocation.
 * Audit log: GENERATED EXCLUSIVELY SERVER-SIDE.
 *   - At dispatch: server logs job_type, device_id, params, timestamp.
 *   - At JOB_RESULT: server logs result status, duration, verification.
 *   - Device sends ZERO log entries. No COMMAND_LOG message type exists.
 *
 * ts field: generated by sender for ordering/debugging only.
 * Server MUST NOT trust ts values from device — use server-side NOW() for DB timestamps.
 */

// ─── Message envelope ────────────────────────────────────────────────────────

export interface WsMessage<T = unknown> {
  type: MessageType;
  payload: T;
  ts: number; // UTC epoch ms — informational only on device→server messages
}

// ─── Message types ────────────────────────────────────────────────────────────

export type MessageType =
  // Device → Server (ECDSA auth flow)
  | "HELLO"             // device sends IMEI+pubKey, server replies CHALLENGE
  | "CHALLENGE_RESPONSE" // device signs challenge, server replies HELLO_ACK
  // Device → Server
  | "REGISTER"          // first install — includes one-time registration code
  | "RECONNECT"         // subsequent connections — includes access_token
  | "TOKEN_REFRESH"     // access_token expired → request new one with refresh_token
  | "HEARTBEAT"         // adaptive: 30s active / 120s idle
  | "JOB_RESULT"        // job execution result (includes VerificationResult)
  | "HEALTH_REPORT"     // explicit health snapshot (beyond heartbeat)
  // NOTE: NO COMMAND_LOG — audit log is generated server-side from dispatch + JOB_RESULT
  | "VISION_REQUEST"    // Phase 3: screenshot → server → VLM provider
  // Server → Device
  | "CHALLENGE"           // server sends nonce for device to sign
  | "HELLO_ACK"           // auth complete — device now connected
  | "REGISTER_ACK"          // registration accepted — includes both tokens
  | "REGISTER_REJECT"       // registration rejected (BLOCKED) — see code field
  | "REGISTRATION_PENDING"  // device created as pending — admin must approve
  | "TOKEN_REFRESH_ACK" // new access_token after refresh
  | "JOB_DISPATCH"      // dispatch job to device
  | "OTA_UPDATE"        // OTA deployment (metadata only — agent handles download)
  | "AUTH_REVOKED"      // device revoked from dashboard — clear tokens, stop
  | "PING"              // application-level ping (separate from WS protocol ping/pong)
  | "VISION_RESULT"     // Phase 3: VLM structured output for device
  | "CONFIG_UPDATE"   // Phase 3: push updated agent config (e.g. VLM settings)
  | "CLOAK_CONFIG"    // Phase 4: push fingerprint/spoofing profile to LSPosed module
  | "KILL_SWITCH";     // Phase 4: server → device — stop all activity immediately

// ─── ECDSA Auth Flow ─────────────────────────────────────────────────────────

export interface HelloPayload {
  /** IMEI (rooted) or hardware-derived UUID */
  imei: string;
  /** PEM-encoded ECDSA P-256 public key */
  publicKeyPem: string;
  /** Device model for logging */
  model: string;
  /** Android version */
  androidVersion: string;
  /** Agent app version */
  agentVersion: string;
  /** User-friendly device name */
  friendlyName?: string;
}

export interface ChallengeResponsePayload {
  /** Challenge nonce from server */
  challenge: string;
  /** Base64-encoded ECDSA signature of the challenge */
  signature: string;
  /** Device ID (for lookup) */
  deviceId?: string;
}

export interface HelloAckPayload {
  /** Server-assigned device UUID */
  deviceId: string;
  /** Optional cloak config for LSPosed module */
  cloakConfig?: {
    fingerprint?: Record<string, string>;
    sensors?: Record<string, unknown>;
  };
}

export interface HelloRejectPayload {
  /** Rejection reason code */
  code: "BLOCKED" | "INVALID_SIGNATURE" | "UNKNOWN_DEVICE" | "PENDING_APPROVAL" | "AUTH_FAILED" | "AWAITING_APPROVAL";
  /** Human-readable message */
  message?: string;
  /** Additional reason details */
  reason?: string;
}

// ─── Device → Server ─────────────────────────────────────────────────────────

export interface RegisterPayload {
  /** Persistent UUID generated on first install, stored in file */
  deviceUuid: string;
  model: string;
  androidVersion: string;
  agentVersion: string;
  /** Optional: location hint from device config (loc_a/b/c/d) */
  locationHint?: string;
  // registrationCode REMOVED — codeless approval flow (admin approves from dashboard)
}

export interface ReconnectPayload {
  deviceUuid: string;
  /** Short-lived access token (24h) */
  accessToken: string;
  lastJobId: string | null;
  lastJobStatus: JobStatus | null;
}

export interface TokenRefreshPayload {
  deviceUuid: string;
  /** Long-lived refresh token (30d) — sent only when access token expired */
  refreshToken: string;
}

export interface HeartbeatPayload {
  deviceUuid: string;
  health: DeviceHealth;
}

export interface JobResultPayload {
  jobId: string;
  /**
   * Informational only — server uses connection.deviceId (authenticated).
   * Device may omit this field.
   */
  deviceUuid?: string;
  status: JobStatus;
  output?: unknown;
  error?: string;
  durationMs: number;
  /**
   * Verification result from Action Verification Cascade.
   * Phase 1: { verified: false, verifiedBy: "none", cascadeLevelsUsed: 0, ... }
   * Phase 2+: populated with actual cascade results.
   */
  verification?: VerificationResult;
}

export interface HealthReportPayload {
  deviceUuid: string;
  health: DeviceHealth;
}

/**
 * Phase 3: Vision request — device sends screenshot to server for VLM processing.
 * Agent has no knowledge of which VLM provider is used — server handles routing.
 *
 * ⚠️ NO `prompt` field — server constructs prompts from templates (anti prompt-injection).
 * Device sends only: jobId, screenshot, requestType, actionType.
 */
export interface VisionRequestPayload {
  jobId: string;
  /** Base64 JPEG screenshot — resized to max 1280px wide on device before sending */
  screenshotBase64: string;
  /** Coarse category of analysis — server selects prompt template based on this */
  requestType: "element_find" | "verify_action" | "screen_understand";
  /** Specific action being performed — for template context (e.g. "tap_like", "scroll_feed") */
  actionType: string;
}

/** Phase 3: Structured element from VLM or AccessibilityService — normalized output */
export interface ScreenElement {
  type: "button" | "text" | "image" | "input" | "container" | "unknown";
  text: string | null;
  contentDescription: string | null;
  bounds: { x: number; y: number; width: number; height: number };
  resourceId: string | null;    // null for VLM-sourced elements
  className: string | null;     // null for VLM-sourced elements
  isClickable: boolean;
  isScrollable: boolean;
  confidence: number;           // 1.0 for UI tree, 0.0-1.0 for VLM
  source: "accessibility" | "vlm";
}

/** Phase 3: VLM response sent back to device */
export interface VisionResultPayload {
  jobId: string;
  elements: ScreenElement[];
  sceneDescription: string;
  detectedState?: string;
}

/** Phase 3: Push updated agent config from server */
export interface ConfigUpdatePayload {
  verificationDefaults?: {
    l1TimeoutMs?: number;
    l2SettleMs?: number;
    l2DiffThreshold?: number;
  };
  heartbeatIdleMs?: number;
  heartbeatActiveMs?: number;
}

/**
 * Verification result — included in every JOB_RESULT (v3).
 * Faza 1: cascadeLevelsUsed=0, verifiedBy="none" (Verification Cascade not yet implemented)
 * Faza 2: L1 + L2 populated
 * Faza 3: L3 (VLM) populated
 */
export interface VerificationResult {
  verified: boolean;
  verifiedBy: "ui_tree" | "pixel_diff" | "vlm" | "none";
  cascadeLevelsUsed: number;   // 0 = no verification (Phase 1), 1-3 = cascade levels
  confidence: number;          // 0.0 - 1.0
  llmTokensUsed: number;       // 0 if no VLM used
  verificationTimeMs: number;
}

// ─── Server → Device ─────────────────────────────────────────────────────────

export interface RegisterAckPayload {
  accessToken: string;
  refreshToken: string;
  deviceId: string;
  accessExpiresAt: number;  // UTC epoch ms
  refreshExpiresAt: number; // UTC epoch ms
}

export interface RegisterRejectPayload {
  reason: string;
  /**
   * Machine-readable rejection code.
   * Device MUST check this — do NOT match on reason text (brittle).
   */
  code: "AWAITING_APPROVAL" | "REGISTRATION_FAILED" | "INVALID_TOKEN" | "INVALID_CODE" | "REVOKED"
      | "BLOCKED" | "APPROVAL_TIMEOUT";
}

export interface TokenRefreshAckPayload {
  accessToken: string;
  accessExpiresAt: number; // UTC epoch ms
}

export interface JobDispatchPayload {
  jobId: string;
  type: JobType;
  params: JobParams;
  timeoutMs?: number;
  /** True if job requires root — device can use for additional safety checks */
  requiresRoot?: boolean;
  /**
   * Verification strategy for this job.
   * Device uses this to decide whether to take beforeScreenshot (L2 requires it).
   * "full_cascade" / "vlm_required" not supported in Phase 2 — device returns
   * verification: { verified: false, verifiedBy: "none" } for unsupported strategies.
   */
  verificationStrategy?: "local_only" | "local_with_screenshot" | "full_cascade" | "vlm_required";
  /** L1 UI tree diff timeout (ms) — how long to wait for UI change before escalating */
  l1TimeoutMs?: number;
  /** L2 settle time (ms) — wait after action before taking afterScreenshot */
  l2SettleMs?: number;
}

export interface OtaUpdatePayload {
  version: string;
  versionCode: number;
  apkUrl: string;
  apkSha256: string;
  /** Base64-encoded APK signature for verification */
  apkSignature: string;
  mandatory: boolean;
  /** If true, allow installing older versionCode than current */
  forceDowngrade?: boolean;
}

// ─── Shared types ─────────────────────────────────────────────────────────────

export interface DeviceHealth {
  batteryLevel: number;
  charging: boolean;
  storageFreeBytes: number;
  memoryAvailableMb?: number;   // Phase 4: Prometheus device memory gauge
  thermalStatus: "nominal" | "light" | "moderate" | "severe" | "critical";
  networkType: "wifi" | "mobile" | "ethernet" | "none";
  networkQuality: "excellent" | "good" | "poor" | "none";
  activeApp?: string;
  agentVersion: string;
}

export type JobStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"
  | "timeout";

export type JobType =
  | "tap"
  | "swipe"
  | "long_press"      // tap and hold for durationMs
  | "type_text"
  | "scroll"
  | "screenshot"
  | "screenshot_for_vlm"  // VLM-optimized screenshot (540x1200, JPEG 85%)
  | "screen_record"
  | "open_app"
  | "open_app_fresh"
  | "close_app"
  | "ui_tree_dump"
  | "press_key"       // navigation buttons: back, home, recents
  | "screen_wake"     // wake screen (turn on display)
  | "screen_off"      // turn off screen / lock
  | "unlock"          // unlock device with PIN/pattern
  | "get_screen_state"// check if screen is on/off/locked
  | "get_clipboard"   // read clipboard text
  | "set_clipboard"   // write text to clipboard
  | "wait_for_idle"   // wait for UI animations to settle
  | "file_push"       // download file from server to device
  | "file_delete"     // delete file on device
  // Root commands — whitelisted only, no generic shell
  // pm_install REMOVED: APK install exclusively through ota_update
  | "pm_uninstall"    // requires confirmRoot=true + dashboard confirmation
  | "reboot"          // requires confirmRoot=true + dashboard confirmation
  | "ota_update"      // signed APK — download, verify, install
  // Skill system (cascade tap)
  | "skill_tap"       // tap at normalized coords from skill
  | "a11y_find_tap"   // find element via A11y and tap
  | "ocr_find_tap"    // find text via ML Kit OCR and tap
  | "cascade_tap"     // VLM-guided tap: screenshot → VLM finds coords → tap
  // Screen detection cascade
  | "ocr_full"       // full-screen ML Kit OCR — returns all blocks, fullText, bounds
  // Workflow execution
  | "workflow_execute"; // execute workflow JSON locally on device

export type JobParams =
  | TapParams
  | SwipeParams
  | LongPressParams
  | TypeTextParams
  | ScrollParams
  | ScreenshotParams
  | ScreenRecordParams
  | OpenAppParams
  | CloseAppParams
  | UiTreeDumpParams
  | PressKeyParams
  | ScreenWakeParams
  | ScreenOffParams
  | UnlockParams
  | GetScreenStateParams
  | GetClipboardParams
  | SetClipboardParams
  | WaitForIdleParams
  | FilePushParams
  | FileDeleteParams
  | PmUninstallParams
  | RebootParams
  | OtaUpdateJobParams
  | SkillTapParams
  | A11yFindTapParams
  | OcrFindTapParams
  | OcrFullParams;

export interface TapParams {
  x: number;
  y: number;
  /** Gaussian jitter radius in px — applied server-side, executed as-is by agent */
  jitterPx?: number;
}

export interface SwipeParams {
  startX: number;
  startY: number;
  endX: number;
  endY: number;
  durationMs: number;
}

export interface TypeTextParams {
  text: string;
}

export interface ScrollParams {
  direction: "up" | "down" | "left" | "right";
  distancePx: number;
  durationMs: number;
}

export interface ScreenshotParams {
  quality?: number; // 1-100, default 80
}

export interface ScreenRecordParams {
  durationMs: number;
  bitrateMbps?: number;
}

export interface OpenAppParams {
  packageName: string;
}

export interface CloseAppParams {
  packageName: string;
}

export interface UiTreeDumpParams {
  packageName?: string;
}

export interface PressKeyParams {
  key: "back" | "home" | "recents";
}

export interface LongPressParams {
  x: number;
  y: number;
  /** Duration in ms, default 1000 */
  durationMs?: number;
}

export interface ScreenWakeParams {
  // No params required — just wakes the screen
}

export interface ScreenOffParams {
  // No params required — turns off/locks the screen
}

export interface UnlockParams {
  /** PIN code (4-6 digits) */
  pin?: string;
  /** Pattern as array of points 0-8 (3x3 grid: 0=top-left, 8=bottom-right) */
  pattern?: number[];
}

export interface GetScreenStateParams {
  // No params required
}

export interface GetClipboardParams {
  // No params required
}

export interface SetClipboardParams {
  text: string;
}

export interface WaitForIdleParams {
  /** Timeout in ms, default 5000 */
  timeoutMs?: number;
}

export interface FilePushParams {
  /** URL or server path to download from */
  localPath: string;
  /** Destination path on device (e.g., /sdcard/DCIM/photo.jpg) */
  remotePath: string;
}

export interface FileDeleteParams {
  /** File path on device to delete */
  remotePath: string;
}

export interface PmUninstallParams {
  packageName: string;
  keepData?: boolean;
}

export interface RebootParams {
  /** Requires explicit dashboard confirmation + confirmRoot=true */
  confirmed: true;
}

/** OTA update — device downloads, verifies SHA256 + signature, then installs */
export interface OtaUpdateJobParams {
  version: string;
  versionCode: number;
  apkUrl: string;
  apkSha256: string;
  /** Base64-encoded RSA signature — verified by agent before install */
  apkSignature: string;
  mandatory: boolean;
  /** If true, allow downgrade — must be explicitly set by server (not device) */
  forceDowngrade?: boolean;
}

// ─── Skill System Params ──────────────────────────────────────────────────────

/** Skill tap — tap at normalized coordinates from skill file */
export interface SkillTapParams {
  /** Normalized X coordinate (0.0 - 1.0) */
  x: number;
  /** Normalized Y coordinate (0.0 - 1.0) */
  y: number;
  /** For audit/debug — which skill element this tap is for */
  skillId?: string;
  buttonId?: string;
  platform?: string;
}

/** A11y find tap — find element via AccessibilityService and tap */
export interface A11yFindTapParams {
  /** Text content to match */
  text?: string;
  /** Content description to match */
  contentDescription?: string;
  /** Class name to match (e.g., android.widget.Button) */
  className?: string;
  /** Resource ID to match (e.g., com.instagram.android:id/like_button) */
  resourceId?: string;
  /** If true, use partial text match (contains) instead of exact */
  partialMatch?: boolean;
}

/** Result from a11y_find_tap — includes the found coordinates */
export interface A11yFindTapResult {
  found: boolean;
  /** Normalized coordinates of found element center (0.0 - 1.0) */
  x?: number;
  y?: number;
  /** Pixel coordinates of found element center */
  pixelX?: number;
  pixelY?: number;
  /** Element bounds in pixels */
  bounds?: { left: number; top: number; right: number; bottom: number };
  /** Matched text or contentDescription */
  matchedText?: string;
}

/** OCR Find & Tap — ML Kit text recognition, find text on screen, tap it */
export interface OcrFindTapParams {
  /** Text to search for on screen */
  searchText: string;
  /** If true, partial match (contains) instead of exact */
  partialMatch?: boolean;
  /** Maximum results to return (default: 1) */
  maxResults?: number;
  /**
   * Language hints for ML Kit (optional).
   * Example: ["ro", "en"] — improves accuracy on Romanian UI
   */
  languageHints?: string[];
}

/** Result from ocr_find_tap */
export interface OcrFindTapResult {
  found: boolean;
  /** Normalized X coordinate of matched text center (0.0 - 1.0) */
  x?: number;
  /** Normalized Y coordinate of matched text center (0.0 - 1.0) */
  y?: number;
  /** Pixel coordinates */
  pixelX?: number;
  pixelY?: number;
  /** The actual text matched (useful for partial matches) */
  matchedText?: string;
  /** Pixel bounds of matched text block */
  bounds?: { left: number; top: number; right: number; bottom: number };
  /** Confidence from ML Kit (0.0 - 1.0) */
  confidence?: number;
  /** How many text blocks were found total on screen */
  totalBlocks?: number;
}

// ─── Screen Detection Cascade Params ─────────────────────────────────────────

/**
 * ocr_full — full-screen ML Kit OCR.
 * Returns all detected text blocks with coordinates.
 * Used by Screen Detection Cascade L2 (ocr.detector.ts).
 */
export interface OcrFullParams {
  // No required params — scans full screen
  /**
   * Language hints for ML Kit (optional).
   * Example: ["ro", "en"] — improves accuracy on Romanian UI text.
   */
  languageHints?: string[];
}

/** Single OCR text block with bounding box and confidence */
export interface OcrBlock {
  /** Full text of this block (all lines joined) */
  text: string;
  /** Bounding box in screen pixels */
  bounds: { left: number; top: number; right: number; bottom: number };
  /** Average confidence across lines in this block (0.0 - 1.0) */
  confidence: number;
  /** Individual lines within this block */
  lines: Array<{
    text: string;
    bounds: { left: number; top: number; right: number; bottom: number };
    confidence: number;
  }>;
}

/**
 * Result from ocr_full.
 *
 * Schema:
 * ```json
 * {
 *   "blocks": [
 *     {
 *       "text": "Action Blocked",
 *       "bounds": { "left": 120, "top": 300, "right": 600, "bottom": 360 },
 *       "confidence": 0.97,
 *       "lines": [{ "text": "Action Blocked", "bounds": {...}, "confidence": 0.97 }]
 *     }
 *   ],
 *   "fullText": "Action Blocked\nThis action was blocked...",
 *   "totalBlocks": 3
 * }
 * ```
 */
export interface OcrFullResult {
  /** All detected text blocks with coordinates */
  blocks: OcrBlock[];
  /** All detected text joined with newlines (for quick full-text search) */
  fullText: string;
  /** Total number of blocks detected */
  totalBlocks: number;
}
