"use strict";
/**
 * shared/protocol/messages.ts
 * WebSocket message types shared between server and dashboard.
 * Android agent uses this as reference (Kotlin implementation mirrors these types).
 *
 * Auth model: Dual token (access 24h + refresh 30d) + server-side revocation.
 * Audit log: GENERATED EXCLUSIVELY SERVER-SIDE.
 *   - At dispatch: server logs job_type, device_id, params, timestamp.
 *   - At JOB_RESULT: server logs result status, duration, verification.
 *   - Device sends ZERO log entries. No COMMAND_LOG message type exists.
 *
 * ts field: generated by sender for ordering/debugging only.
 * Server MUST NOT trust ts values from device — use server-side NOW() for DB timestamps.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=messages.js.map