/**
 * modules/accounts/accounts.service.ts
 * Social media account management — CRUD, lifecycle, ban detection, credential vault.
 *
 * Security:
 * - Credentials NEVER stored plain text
 * - `encryption_key_ref` → Vault reference (prod) or env var (dev)
 * - Actual credential encryption is AES-256-GCM on client (Android TokenStore pattern)
 *   Server stores only Vault reference; credentials encrypted on device + in Vault
 * - UNIQUE(platform, device_id) enforced at DB level + service level (clear error)
 *
 * Lifecycle: created → warming_up → active → paused → banned (terminal)
 *
 * Reference: ARCHITECTURE_AUDIT_v3.md §15 constraint #2, #13
 */

import { getDb } from "../../db/client";
import { v4 as uuidv4 } from "uuid";
import { accountBanned, accountChallenged } from "../observability/metrics";
import { alerting } from "../observability/alerts";
import { researchService } from "../research/research.service";
import {
  getResourceLifecycleTransitionToState,
} from "../lifecycle/lifecycle.service";

// ─── Types ────────────────────────────────────────────────────────────────────

export type AccountStatus = string;

export interface Account {
  id:               string;
  platform:         string;
  username:         string;
  deviceId:         string;
  clientId:         string | null;
  type:             string;   // "business" | "farming"
  status:           AccountStatus;
  /** Vault reference for credentials — format: "vault:accounts/{accountId}/creds" */
  encryptionKeyRef: string;
  ageDays:          number;   // Computed: (now - created_at) / 86400
  sessionCount:     number;
  totalActions:     number;
  lastActiveAt:     string | null;
  /** Simulated timezone for HBE session scheduling */
  simulatedTimezone: string;
  createdAt:        string;
  notes:            string | null;
  /** Profile metrics synced from research_profile jobs */
  metrics:          Record<string, unknown>;
  /** Risk/ban detection flags */
  flags:            Record<string, unknown>;
  /** Account-level strategy generated by Marketer */
  strategy:         Record<string, unknown> | null;
}

export interface CreateAccountInput {
  platform:          string;
  username:          string;
  deviceId:          string;
  clientId?:         string;
  type?:             "business" | "farming";
  simulatedTimezone?: string;
  /** Optional initial notes */
  notes?:            string;
}

export interface AccountStats {
  totalAccounts:      number;
  byStatus:           Record<AccountStatus, number>;
  byPlatform:         Record<string, number>;
  activeAccounts:     number;
  bannedAccounts:     number;
  challengedAccounts: number;
}

// ─── Service ──────────────────────────────────────────────────────────────────

export class AccountsService {
  // ─── CRUD ─────────────────────────────────────────────────────────────────

  async create(input: CreateAccountInput): Promise<Account> {
    const db = getDb();
    const id = uuidv4();

    // Enforce UNIQUE(platform, device_id) at service layer — clear error before DB constraint
    const existing = await db.query(
      "SELECT id FROM accounts WHERE platform = $1 AND device_id = $2",
      [input.platform, input.deviceId]
    );
    if (existing.rows.length > 0) {
      throw new Error(
        `Device ${input.deviceId} already has a ${input.platform} account ` +
        `(id=${existing.rows[0].id}). Max 1 account per platform per device.`
      );
    }

    // Vault reference: server never stores plaintext credentials
    // Format: "vault:accounts/{accountId}/creds"
    // Device will encrypt credentials and store in Vault at this path
    const encryptionKeyRef = `vault:accounts/${id}/creds`;

    const result = await db.query(
      `INSERT INTO accounts
         (id, platform, username, device_id, client_id, type, encryption_key_ref, simulated_timezone, notes)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING *`,
      [
        id,
        input.platform,
        input.username,
        input.deviceId,
        input.clientId ?? null,
        input.type ?? "farming",
        encryptionKeyRef,
        input.simulatedTimezone ?? "Europe/Bucharest",
        input.notes ?? null,
      ]
    );
    const account = rowToAccount(result.rows[0]);

    // Auto-research: queue a profile research job immediately after account creation.
    // Runtime behavior is selected from the PostgreSQL capability catalog.
    // Fire-and-forget — don't block account creation if research queue is full.
    researchService.requestResearch(
      "research_profile",
      { username: account.username, platform: account.platform, deviceId: account.deviceId },
      1  // Slightly elevated priority vs. nightly batch (0)
    ).then(jobId => {
      console.log(`[accounts] Auto-research queued for @${account.username} (${account.platform}): job ${jobId}`);
    }).catch(err => {
      console.warn(`[accounts] Auto-research queue failed for @${account.username}:`, (err as Error).message);
    });

    return account;
  }

  async get(id: string): Promise<Account | null> {
    const db = getDb();
    const result = await db.query("SELECT * FROM accounts WHERE id = $1", [id]);
    if (result.rows.length === 0) return null;
    return rowToAccount(result.rows[0]);
  }

  async list(
    deviceId?:  string,
    platform?:  string,
    status?:    AccountStatus,
    page = 1,
    pageSize = 50
  ): Promise<{ items: Account[]; total: number }> {
    const db = getDb();
    const conditions: string[] = [];
    const values: unknown[] = [];

    const add = (col: string, val: unknown) => {
      values.push(val);
      conditions.push(`${col} = $${values.length}`);
    };
    if (deviceId) add("device_id", deviceId);
    if (platform) add("platform",  platform);
    if (status)   add("status",    status);

    const where = conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : "";
    values.push(pageSize, (page - 1) * pageSize);

    const [rows, countRow] = await Promise.all([
      db.query(`SELECT * FROM accounts ${where} ORDER BY created_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values),
      db.query(`SELECT COUNT(*) FROM accounts ${where}`, values.slice(0, -2)),
    ]);

    return {
      items: rows.rows.map(rowToAccount),
      total: parseInt(countRow.rows[0].count, 10),
    };
  }

  async getStats(): Promise<AccountStats> {
    const db = getDb();
    const rows = await db.query(
      "SELECT platform, status, COUNT(*) as count FROM accounts GROUP BY platform, status"
    );
    const stats: AccountStats = {
      totalAccounts:      0,
      byStatus:           {} as Record<AccountStatus, number>,
      byPlatform:         {},
      activeAccounts:     0,
      bannedAccounts:     0,
      challengedAccounts: 0,
    };
    for (const row of rows.rows) {
      const count = parseInt(row.count, 10);
      stats.totalAccounts += count;
      stats.byStatus[row.status as AccountStatus] = (stats.byStatus[row.status as AccountStatus] ?? 0) + count;
      stats.byPlatform[row.platform] = (stats.byPlatform[row.platform] ?? 0) + count;
    }
    const capabilityCounts = await db.query(
      `SELECT
         COALESCE(SUM(counts.count) FILTER (WHERE state.dispatchable), 0)::int AS active,
         COALESCE(SUM(counts.count) FILTER (WHERE state.terminal), 0)::int AS terminal,
         COALESCE(SUM(counts.count) FILTER (WHERE state.manual AND NOT state.terminal), 0)::int AS manual
       FROM lifecycle_resource_bindings binding
       JOIN lifecycle_state_definitions state ON state.lifecycle_key = binding.lifecycle_key
       LEFT JOIN LATERAL (
         SELECT COUNT(*)::int AS count FROM accounts account WHERE account.status = state.status
       ) counts ON TRUE
       WHERE binding.resource_table = 'accounts'::regclass
         AND binding.state_column = 'status'::name`,
    );
    stats.activeAccounts = Number(capabilityCounts.rows[0]?.active ?? 0);
    stats.bannedAccounts = Number(capabilityCounts.rows[0]?.terminal ?? 0);
    stats.challengedAccounts = Number(capabilityCounts.rows[0]?.manual ?? 0);
    return stats;
  }

  // ─── Lifecycle transitions ─────────────────────────────────────────────────

  async updateStatus(id: string, status: AccountStatus, notes?: string): Promise<Account | null> {
    const db = getDb();
    const account = await this.get(id);
    if (!account) return null;
    if (account.status !== status) {
      const transition = await getResourceLifecycleTransitionToState("accounts", account.status, status, "status", db);
      if (!transition) throw new Error("Requested account lifecycle transition is not configured");
    }
    const result = await db.query(
      `UPDATE accounts SET status = $1, notes = COALESCE($2, notes) WHERE id = $3 RETURNING *`,
      [status, notes ?? null, id]
    );
    return rowToAccount(result.rows[0]);
  }

  async delete(id: string): Promise<boolean> {
    const db = getDb();
    const result = await db.query(
      `DELETE FROM accounts WHERE id = $1 RETURNING id`,
      [id]
    );
    return (result.rowCount ?? 0) > 0;
  }

  async recordSession(id: string): Promise<void> {
    const db = getDb();
    await db.query(
      `UPDATE accounts
       SET session_count   = session_count + 1,
           last_active_at  = NOW(),
           status          = COALESCE(
             lifecycle_transition_target(
               'accounts'::regclass,
               status,
               '{"automatic":true,"markStarted":true}'::jsonb
             ),
             status
           )
       WHERE id = $1`,
      [id]
    );
  }

  async recordAction(id: string, actionCount = 1): Promise<void> {
    const db = getDb();
    await db.query(
      "UPDATE accounts SET total_actions = total_actions + $1 WHERE id = $2",
      [actionCount, id]
    );
  }

  /**
   * Flag account as challenged — needs manual review.
   * Called by ban detection logic (Phase 4 full automation).
   */
  async flagChallenged(id: string, reason: string): Promise<void> {
    const db = getDb();
    const result = await db.query(
      `UPDATE accounts
       SET status = lifecycle_transition_target(
             'accounts'::regclass,
             status,
             '{"targetManual":true,"targetTerminal":false,"automatic":true}'::jsonb
           ),
           notes = $1
       WHERE id = $2
         AND NOT lifecycle_state_matches('accounts'::regclass, status, '{"terminal":true}'::jsonb)
         AND lifecycle_transition_target(
               'accounts'::regclass,
               status,
               '{"targetManual":true,"targetTerminal":false,"automatic":true}'::jsonb
             ) IS NOT NULL
       RETURNING platform`,
      [reason, id]
    );
    if ((result.rowCount ?? 0) > 0) {
      const platform = result.rows[0].platform as string;
      accountChallenged?.labels(platform).inc();
      alerting.accountChallenged(id, platform, reason).catch(() => {});
      console.warn(`[accounts] Account ${id} flagged as challenged: ${reason}`);
    }
  }

  /**
   * Mark account as banned — terminal state.
   */
  async markBanned(id: string, reason: string): Promise<void> {
    const db = getDb();
    const result = await db.query(
      `UPDATE accounts
       SET status = lifecycle_transition_target(
             'accounts'::regclass,
             status,
             '{"targetTerminal":true,"automatic":true}'::jsonb
           ),
           notes = $1
       WHERE id = $2
         AND lifecycle_transition_target(
               'accounts'::regclass,
               status,
               '{"targetTerminal":true,"automatic":true}'::jsonb
             ) IS NOT NULL
       RETURNING platform`,
      [reason, id]
    );
    if ((result.rowCount ?? 0) > 0) {
      const platform = result.rows[0].platform as string;
      accountBanned?.labels(platform, reason.slice(0, 60)).inc();
      alerting.accountBanned(id, platform, reason).catch(() => {});
      console.warn(`[accounts] Account ${id} BANNED: ${reason}`);
    }
  }

  /**
   * Get accounts ready for workflow execution (active + warming_up).
   * Used by scheduler to pick next account for a session.
   */
  async getWorkableAccounts(platform?: string): Promise<Account[]> {
    const db = getDb();
    const where = platform ? "AND platform = $1" : "";
    const values = platform ? [platform] : [];
    const rows = await db.query(
      `SELECT * FROM accounts
       WHERE lifecycle_state_matches('accounts'::regclass, status, '{"dispatchable":true}'::jsonb)
       ${where}
       ORDER BY last_active_at ASC NULLS FIRST, created_at ASC`,
      values
    );
    return rows.rows.map(rowToAccount);
  }

  /**
   * Promote account from warming_up to active if age >= 14 days.
   * Called by daily scheduler.
   */
  async promoteWarmupAccounts(): Promise<number> {
    const db = getDb();
    const result = await db.query(
      `UPDATE accounts
       SET status = lifecycle_transition_target(
             'accounts'::regclass,
             status,
             '{"targetDispatchable":true,"automatic":true}'::jsonb
           )
       WHERE lifecycle_transition_target(
               'accounts'::regclass,
               status,
               '{"targetDispatchable":true,"automatic":true}'::jsonb
             ) IS NOT NULL
         AND created_at <= NOW() - INTERVAL '14 days'
       RETURNING id`
    );
    const promoted = result.rowCount ?? 0;
    if (promoted > 0) {
      console.log(`[accounts] Promoted ${promoted} accounts from warming_up → active`);
    }
    return promoted;
  }
}

// ─── Row mapper ───────────────────────────────────────────────────────────────

function rowToAccount(row: Record<string, unknown>): Account {
  const createdAt = row.created_at as Date;
  const ageDays   = Math.floor((Date.now() - createdAt.getTime()) / 86_400_000);
  return {
    id:                row.id as string,
    platform:          row.platform as string,
    username:          row.username as string,
    deviceId:          row.device_id as string,
    clientId:          (row.client_id as string) ?? null,
    type:              (row.type as string) ?? "farming",
    status:            row.status as AccountStatus,
    encryptionKeyRef:  row.encryption_key_ref as string,
    ageDays,
    sessionCount:      (row.session_count as number) ?? 0,
    totalActions:      (row.total_actions as number) ?? 0,
    lastActiveAt:      row.last_active_at ? (row.last_active_at as Date).toISOString() : null,
    simulatedTimezone: (row.simulated_timezone as string) ?? "Europe/Bucharest",
    createdAt:         createdAt.toISOString(),
    notes:             (row.notes as string) ?? null,
    metrics:           (row.metrics as Record<string, unknown>) ?? {},
    flags:             (row.flags as Record<string, unknown>) ?? {},
    strategy:          (row.strategy as Record<string, unknown>) ?? null,
  };
}

export const accountsService = new AccountsService();
